test_homepage:
    path:     /hello/{name}
    defaults: { _controller: TestBundle:Default:index }

test_user:
    path:     /user/index.php
    defaults: { _controller: TestBundle:User:index }


test_articles:
    path:     /user/articles/{articulo}
    defaults: { _controller: TestBundle:User:articles }

test_entity:
    path:     /user/entity
    defaults: { _controller: TestBundle:Entity:entity }

test_view:
    path:     /user/view/{id}
    defaults: { _controller: TestBundle:Entity:view }    


test_twig:
    path:     /user/consult
    defaults: { _controller: TestBundle:Entity:consult }    

test_add:
    path:     /user/add
    defaults: { _controller: TestBundle:Entity:add }    

test_create:
    path:     /user/create
    defaults: { _controller: TestBundle:Entity:create }    

test_delete:
    path:     /user/delete
    defaults: { _controller: TestBundle:Entity:delete } 

test_viewtask:
    path:     /task/tasks
    defaults: { _controller: TestBundle:Entity:viewtask }

test_createtask:
    path:     /task/createtask
    defaults: { _controller: TestBundle:Entity:createtask }
    
test_addtask:
    path:     /task/addtask
    defaults: { _controller: TestBundle:Entity:addtask }
    
