# Users

test_twig:
    path:     /user/consult
    defaults: { _controller: TestBundle:Entity:consult }    

test_add:
    path:     /user/add
    defaults: { _controller: TestBundle:Entity:add }    

test_create:
    path:     /user/create
    defaults: { _controller: TestBundle:Entity:create }    

test_delete:
    path:     /user/delete
    defaults: { _controller: TestBundle:Entity:delete } 

test_userdatable:
    path: /user/datatable
    defaults: {_controller: TestBundle:Entity:getUsersDatatable}


# Tasks

test_viewtask:
    path:     /task/tasks
    defaults: { _controller: TestBundle:Entity:viewtask }

test_createtask:
    path:     /task/createtask
    defaults: { _controller: TestBundle:Entity:createtask }
    
test_addtask:
    path:     /task/addtask
    defaults: { _controller: TestBundle:Entity:addtask }
    
test_deletetask:
    path:     /task/deletetask
    defaults: { _controller: TestBundle:Entity:deletetask }

test_mytask:
    path:     /task/mytask
    defaults: { _controller: TestBundle:Entity:mytask }

test_taskdatatable:
    path:     /task/taskdatatable
    defaults: {_controller: TestBundle:Entity:getTaskDatatable}

test_detailtask:
    path:     /task/detailtask
    defaults: {_controller: TestBundle:Entity:detailTask}

# Autentication

test_user_homepage:
    path:     /
    defaults: { _controller: TestBundle:Entity:home }

test_user_login:
    path:     /login
    defaults: { _controller: TestBundle:Security:login }

test_user_login_check:
    path:     /login_check
    defaults: { _controller: TestBundle:Security:loginCheck }

test_user_logout:
    path:     /logout  