# Users

test_twig:
    path:     /user/consult
    defaults: { _controller: TestBundle:Entity:consult }    

test_add:
    path:     /user/add
    defaults: { _controller: TestBundle:Entity:add }    

test_create:
    path:     /user/create
    defaults: { _controller: TestBundle:Entity:create }    

test_delete:
    path:     /user/delete
    defaults: { _controller: TestBundle:Entity:delete } 

# Tasks

test_viewtask:
    path:     /task/tasks
    defaults: { _controller: TestBundle:Entity:viewtask }

test_createtask:
    path:     /task/createtask
    defaults: { _controller: TestBundle:Entity:createtask }
    
test_addtask:
    path:     /task/addtask
    defaults: { _controller: TestBundle:Entity:addtask }
    
test_deletetask:
    path:     /user/deletetask
    defaults: { _controller: TestBundle:Entity:deletetask }

test_mytask:
    path:     /user/mytask
    defaults: { _controller: TestBundle:Entity:mytask }

# Autentication

test_user_homepage:
    path:     /
    defaults: { _controller: TestBundle:Entity:home }

test_user_login:
    path:     /login
    defaults: { _controller: TestBundle:Security:login }

test_user_login_check:
    path:     /login_check
    defaults: { _controller: TestBundle:Security:loginCheck }

test_user_logout:
    path:     /logout  