# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       our_db_provider:
            entity:
                class: TestBundle:User 
                property: username

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                # field names for the username and password fields:
                username_parameter: _username
                password_parameter: _password
                # default_target_path: default_security_target
                # always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login
        dev:
            pattern: ^/((profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    encoders:
        TestBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user, roles: ROLE_ADMIN }
        # - { path: ^/user/add, role: ADMIN }
        # - { path: ^/user/create, role: ADMIN }
        # - { path: ^/user/delete, role: ADMIN }

        # - { path: ^/task/tasks, role: ADMIN }
        # - { path: ^/task/createtask, role: ADMIN }
        # - { path: ^/task/addtask, role: ADMIN }
        # - { path: ^/task/view, role: [ADMIN, user] }
        # - { path: ^/task/delete, role: ADMIN } 