<?php

namespace TestBundle\Repository;

/**
 * usuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuRepository extends \Doctrine\ORM\EntityRepository
{
}
